name: CICDWorkFlow

on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  myflow:
    #if: ${{ !contains(github.event.head_commit.message, '#norun') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get the codebase
        uses: actions/checkout@v4

      - name: Security Scan By Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'scan-results.txt'
          severity: 'HIGH'
      
      - name: Get scan results
        id: get-scan-result
        run: |
          echo "scan-result=$([ -s scan-results.txt ] && echo '1' || echo '0')"
          echo "scan-result=$([ -s scan-results.txt ] && echo '1' || echo '0')" >> $GITHUB_OUTPUT
   
      - name: Scan alert to slack
        if: steps.get-scan-result.outputs.scan-result == '1' 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Scan failed - Sun TianRui"
          SLACK_MESSAGE: "Failed trivy scan, see uploaded report"
          SLACK_COLOR: "failure"

      - name: Submit Trivy report result to slack
        if: steps.get-scan-result.outputs.scan-result == '1' 
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: scan-results.txt
      
      - name: Control the Flow Exit
        if: steps.get-scan-result.outputs.scan-result == '1' 
        run: exit 1

      - name: Start QEMU
        uses: docker/setup-qemu-action@v3

      - name: Start Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authorization Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Docker Image Build and Push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: raysun777/ci-cd-workshop:${{ github.sha }}

      - name: Setup Image Signing Tool
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'
      
      - name: Sign Docker Image
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY raysun777/ci-cd-workshop:${{ github.sha }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        
      - name: Slack Notification for Success msg
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "Image build and signed"
          SLACK_MESSAGE: |
            *Name:* Sun TianRui
            *Matriculation:* A0290889E
            *Email:* E1327920@u.nus.edu
            *Git:* https://github.com/Rayss7/cicd
            *Docker:* https://hub.docker.com/repository/docker/raysun777/ci-cd-workshop/general                
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

