name: workflow

on: 
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          format: 'table'
          input: /github/workspace/vuln-image.tar
          severity: 'HIGH'
          output: 'trivy_report.txt'
          
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: "failure"
          SLACK_MESSAGE: "Failed trivy scan, see upload report"

      - name: Upload file to Slack
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          content: 'file content'
          file_type: 'text'
          file_name: 'text.txt'
          title: 'title of file'
          initial_comment: 'post by slack-upload-file'

      - name: Exit Workflow 
        run: exit 1 